# Generated by Django 3.0.8 on 2021-04-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vrp', '0003_auto_20210420_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='City',
        ),
    ]
